# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\"3\n\x0fOperationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x0bTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"5\n\x11\x43reateTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\"5\n\x11UpdateTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\"\\\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\")\n\x08TermList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term2\xaa\x02\n\x0fGlossaryService\x12/\n\x08GetTerms\x12\x0f.glossary.Empty\x1a\x12.glossary.TermList\x12\x30\n\x07GetTerm\x12\x15.glossary.TermRequest\x1a\x0e.glossary.Term\x12\x39\n\nCreateTerm\x12\x1b.glossary.CreateTermRequest\x1a\x0e.glossary.Term\x12\x39\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x0e.glossary.Term\x12>\n\nDeleteTerm\x12\x15.glossary.TermRequest\x1a\x19.glossary.OperationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_OPERATIONRESULT']._serialized_start=37
  _globals['_OPERATIONRESULT']._serialized_end=88
  _globals['_TERMREQUEST']._serialized_start=90
  _globals['_TERMREQUEST']._serialized_end=117
  _globals['_CREATETERMREQUEST']._serialized_start=119
  _globals['_CREATETERMREQUEST']._serialized_end=172
  _globals['_UPDATETERMREQUEST']._serialized_start=174
  _globals['_UPDATETERMREQUEST']._serialized_end=227
  _globals['_TERM']._serialized_start=229
  _globals['_TERM']._serialized_end=321
  _globals['_TERMLIST']._serialized_start=323
  _globals['_TERMLIST']._serialized_end=364
  _globals['_GLOSSARYSERVICE']._serialized_start=367
  _globals['_GLOSSARYSERVICE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
